inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.3

Layout/EmptyLineBetweenDefs:
  Enabled: false

# Currently disabled, it conflicts with `rubocop --auto-gen-config`
# Metrics/LineLength:
#   Max: 120
#   AllowHeredoc: false

RSpec/FilePath:
  CustomTransform:
    GraphQL: 'graphql'

Style/AsciiComments:
  Enabled: false
Style/SpecialGlobalVars:
  Exclude:
    - 'solidus_graphql_api.gemspec'
